lang:
  kick-whitelist: "&dKivo &c您没有白名单，请先加群：&a481121567&c申请获得白名单。"
  kick-banned: "&dKivo &c诶哟？服务器似乎不欢迎您诶？"
  banned-broadcast: "&8* &f%player%似乎想进来游玩喔。"
  join-message: "&8+ &f%player%加入了游戏."
  quit-message: "&8- &f%player%断开了连接."
options:
  world-alias:
    world: "&a主世界"
    world_nether: "&c下界"
    world_the_end: "&7末地"
modules:
  here:
    description: "&8| &f!here &7- &6向全服玩家显示你当前的坐标."
    message: "&8* &f%player%处于&7[&fX:&a%player_X%&8,&fY:&a%player_Y%&8,&fZ:&a%player_Z%&8,&f世界:&a%player_World%&7]"
    usage: "!here"
    enabled: true
  mention:
    description: "&8| &f@<玩家名> &7- &6艾特一个玩家."
    complete: "@"
    message:
      To:
        type: title
        title: "&6&l有人@你"
        subTitle: "&7%player%提到了你."
        fadeIn: 20
        stay: 20
        fadeOut: 20
      From:
        type: none
    sound: "BLOCK_AMETHYST_CLUSTER_HIT"
    enabled: true
  seed:
    description: "&8| &f!seed &7- &6查看当前世界的种子."
    message: "&8* &f种子: &7[&a%seed%&7]"
    usage: "!seed"
    enabled: true
  teleport:
    description: "&8| &f!t <玩家名> &7- &6请求传送至玩家身旁.\n&8| &f!th <玩家名> &7- &6请求玩家传送至你身旁."
    message:
      To:
        type: title
        title: "&6&l%player%请求传送到你身旁"
        subTitle: "&7!yes 同意 &f| &7!no 拒绝."
        fadeIn: 20
        stay: 40
        fadeOut: 20
      From:
        type: title
        title: "&6&l%player%请求你传送到TA身旁"
        subTitle: "&7!yes 同意 &f| &7!no 拒绝."
        fadeIn: 20
        stay: 40
        fadeOut: 20
    commands:
      teleport: "!t"
      teleportHere: "!th"
      accept: "!yes"
      deny: "!no"
    sound: "BLOCK_ANVIL_BREAK"
    enabled: true