lang:
  kick-whitelist: "&c您没有白名单，请先加群申请白名单\n&7QQ群: &f&n481121567"
  kick-banned: "&c诶哟？服务器似乎不欢迎您诶？\n&c爱作弊的大哥哥"
  banned-broadcast: "&8* &f%player%似乎想进来游玩喔。"
  join-message: "&8+ &f%player%加入了游戏."
  quit-message: "&8- &f%player%断开了连接."
  reload-succeed: "&8* &f插件已重载完毕."
  tp-to: "&8* &f已发送传送请求."
  tp-succeed: "&8* &f传送成功."
  tp-accept: "&8* &f已接受传送请求."
  tp-deny: "&8* &f已拒绝了你的传送请求."
  tp-deny-from: "&8* &f传送请求已被拒绝."
  tp-cancel: "&8* &f请求已超时."
  tp-noquest: "&8* &f似乎没有传送请求喔."
  tp-too-many: "&8* &f休息一下吧，阿伟."
  tp-to-self: "&8* &f无法自己传送自己."
  sethome: "&8* &f已设置家."
  home: "&8* &f已回到家."
  no-home: "&8* &f你得先设置个家才行啊."
  save: "&8* &f已保存坐标."
  del: "&8* &f已删除坐标."
  unknown-loc: "&8* &f未知的坐标."
  list-key: "&8* &7%loc_Name%:&f%loc%"
options:
  world-alias:
    world: "&a主世界"
    world_nether: "&c下界"
    world_the_end: "&7末地"
modules:
  here:
    description: "&8| &f!here &7- &6向全服玩家显示你当前的坐标."
    message: "&8* &f%player%处于&7[&fX:&a%player_X%&8,&fY:&a%player_Y%&8,&fZ:&a%player_Z%&8,&f世界:&a%player_World%&7]"
    usage: "!here"
    enabled: true
  mention:
    description: "&8| &f@<玩家名> &7- &6艾特一个玩家."
    complete: "@"
    message:
      To:
        # [title|actionbar|text]
        type: title
        title: "&6&l有人@你"
        subTitle: "&7%player%提到了你."
        fadeIn: 20
        stay: 20
        fadeOut: 20
        dnd:
          # [actionbar|text]
          type: actionbar
          text: "%player%提到了你"
      From:
        type: none
    sound: "BLOCK_AMETHYST_CLUSTER_HIT"
    enabled: true
  seed:
    description: "&8| &f!seed &7- &6查看当前世界的种子."
    message: "&8* &f种子: &7[&a%seed%&7]"
    usage: "!seed"
    enabled: true
  dnd:
    description: "&8| &f!dnd &7- &6切换免打扰状态."
    message:
      open: "&8* &f已开启免打扰."
      close: "&8* &f已关闭免打扰."
    toggle: "!dnd"
    enabled: true
  teleport:
    description: "&8| &f!t <玩家名> &7- &6请求传送至玩家身旁.\n&8| &f!th <玩家名> &7- &6请求玩家传送至你身旁."
    message:
      To:
        type: title
        title: "&6&l%player%请求传送到你身旁"
        subTitle: "&7!yes 同意 &f| &7!no 拒绝."
        fadeIn: 20
        stay: 40
        fadeOut: 20
      From:
        type: title
        title: "&6&l%player%请求你传送到TA身旁"
        subTitle: "&7!yes 同意 &f| &7!no 拒绝."
        fadeIn: 20
        stay: 40
        fadeOut: 20
    commands:
      teleport: "!t"
      teleportHere: "!th"
      accept: "!yes"
      deny: "!no"
    sound: "BLOCK_ANVIL_BREAK"
    time: 120
    enabled: true
  home:
    description: "&8| &f!sethome &7- &6将你所在位置设置为家.\n&8| &f!home &7- &6回到家."
    commands:
      sethome: "!sethome"
      home: "!home"
    sound: "AMBIENT_UNDERWATER_ENTER"
    enabled: true
  dead:
    description: "&8| &f!dead &7- &6查看你的死亡坐标."
    message: "&8* &f你的死亡坐标为&7[&fX:&a%player_Dead_X%&8,&fY:&a%player_Dead_Y%&8,&fZ:&a%player_Dead_Z%&8,&f世界:&a%player_Dead_World%&7]"
    usage: "!dead"
    enabled: true
  skip:
    description: "&8| &f!sleep &7- &6可以查看当前世界游戏时刻."
    message: "&8* &f当前世界游戏时刻为: &a%tick%"
    usage: "!sleep"
    enabled: true
  save:
    description: "&8| &f!save <坐标名> &7- &6保存坐标.\n&8| &f!del <坐标名> &7- &6移除坐标.\n&8| &f!list &7- &6列出所有坐标"
    commands:
      save: "!save"
      del: "!del"
      list: "!list"
    enabled: true
  score:
    description: "&8| &f!score &7- &6打开记分板播报."
    message:
      open: "&8* &f已开启记分板."
      close: "&8* &f已关闭记分板."
    toggle: "!score"
    board:
      top: 15
      # TICK
      update-time: 20
    # SECOND
    time: 60
    enabled: true